import Head from "next/head";

import HomePage from "../components/home/Home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kart Bazar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lobster&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <div>
          <div className="container">
            <HomePage />
          </div>
        </div>
      </main>
    </>
  );
}
