import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../components/share/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Kart Bazar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Header />
          <h4 className="test">Hello welcome</h4>
        </div>
      </main>
    </>
  );
}
